# 2021-09-06

파이썬 Exception과 관련해서 새롭게 배운 점이 있다. Exception을 설정해주더라도 내부에서 Exception이 새로 발생하면 그것도 따로 처리를 해줘야 한다는 것. 굉장히 단순한 내용이었는데, 여지껏 그걸 잘못 이해하고 있었다.

## 참고
- https://stackoverflow.com/questions/6470428/catch-multiple-exceptions-in-one-line-except-block